// Emits assets/banner.svg (dark) and assets/banner-light.svg (light) from one template,
// so the two never drift. Palette from the portfolio (reboot-2 branch): ink, paper,
// pebble, grey, and a single colour, green. Run: node scripts/banner.mjs
import { writeFileSync } from 'node:fs';

const SANS = "Archivo, 'Arial Black', 'Helvetica Neue', Arial, sans-serif";
const MONO = "'IBM Plex Mono', ui-monospace, 'SF Mono', Consolas, monospace";
const W = 1060, H = 280;

const cross = (x, y, c) =>
  `<path d="M${x - 7} ${y}h14M${x} ${y - 7}v14" stroke="${c}" stroke-width="1.2"/>`;

function banner(t) {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${H}" width="${W}" height="${H}" role="img" aria-label="Sitraka Rasatarivony, full-stack TypeScript developer, Antananarivo.">
  <!-- Generated by scripts/banner.mjs: do not edit by hand. -->
  <rect width="${W}" height="${H}" fill="${t.bg}"/>
  ${cross(28, 28, t.rule)} ${cross(W - 28, 28, t.rule)} ${cross(28, H - 28, t.rule)} ${cross(W - 28, H - 28, t.rule)}

  <text x="56" y="70" font-family="${MONO}" font-size="12" font-weight="500" letter-spacing="1.6" fill="${t.muted}">SITRAKA RASATARIVONY — ANTANANARIVO, MADAGASCAR</text>

  <text x="52" y="152" font-family="${SANS}" font-size="74" font-weight="900" letter-spacing="-2.5" fill="${t.text}">Full-stack</text>
  <rect x="52" y="172" width="452" height="72" fill="${t.block}"/>
  <text x="62" y="230" font-family="${SANS}" font-size="74" font-weight="900" letter-spacing="-2.5" fill="${t.onBlock}">TypeScript.</text>

  <text x="${W - 72}" y="160" text-anchor="end" font-family="${SANS}" font-size="150" font-weight="900" fill="none" stroke="${t.text}" stroke-width="1.4" letter-spacing="-4">3</text>
  <text x="${W - 72}" y="196" text-anchor="end" font-family="${MONO}" font-size="12" letter-spacing="1.2" fill="${t.muted}">YEARS OF EXPERIENCE</text>
  <text x="${W - 72}" y="214" text-anchor="end" font-family="${MONO}" font-size="12" letter-spacing="1.2" fill="${t.muted}">INTERNSHIP INCLUDED</text>

  <g font-family="${MONO}" font-size="13" fill="${t.text}">
    ${(() => {
      // Right-aligned under the figure, 10px apart; about 7.8px per mono glyph at 13px.
      let x = W - 72;
      return ['PostgreSQL', 'React', 'NestJS'].map((m) => {
        const w = Math.round(m.length * 7.8 + 28);
        x -= w;
        const pill = `<rect x="${x}" y="226" width="${w}" height="28" rx="14" fill="none" stroke="${t.text}" stroke-width="1"/><text x="${x + 14}" y="245">${m}</text>`;
        x -= 10;
        return pill;
      }).reverse().join('\n    ');
    })()}
  </g>

  <text transform="translate(${W - 34} ${H / 2}) rotate(90)" text-anchor="middle" font-family="${MONO}" font-size="10" letter-spacing="2" fill="${t.muted}">SITRAKARASATA.PAGES.DEV</text>
</svg>
`;
}

// Green carries text only on ink; on the light variant the green block takes ink text.
const dark = { bg: '#121212', text: '#ECECE8', muted: '#B9B9B3', rule: '#55554F', block: '#C8F169', onBlock: '#121212' };
const light = { bg: '#ECECE8', text: '#121212', muted: '#55554F', rule: '#B9B9B3', block: '#C8F169', onBlock: '#121212' };

writeFileSync(new URL('../assets/banner.svg', import.meta.url), banner(dark));
writeFileSync(new URL('../assets/banner-light.svg', import.meta.url), banner(light));
