// Measures the live demos and redraws the latency strip.
//
// Run by .github/workflows/metrics.yml, which publishes the output to the
// `metrics` branch as a single always-amended commit, so this repository's
// history never accumulates machine noise.
//
// Usage: node scripts/measure.mjs <out-dir>
//   reads  <out-dir>/history.json   (carried over from the previous run)
//   writes <out-dir>/history.json, latency.svg, latency-light.svg

import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const OUT = process.argv[2] ?? 'out'
const KEEP = 40
const SAMPLES = 5

const TARGETS = [
  { key: 'cine-taste', url: 'https://cine-taste-sr.vercel.app/' },
  { key: 'immo-grant', url: 'https://immo-grant.vercel.app/' }
]

const median = (xs) => {
  const s = [...xs].sort((a, b) => a - b)
  return s.length % 2 ? s[(s.length - 1) / 2] : Math.round((s[s.length / 2 - 1] + s[s.length / 2]) / 2)
}

const timed = async (url) => {
  const t0 = performance.now()
  const res = await fetch(url, { redirect: 'follow', headers: { 'user-agent': 'profile-metrics' } })
  await res.arrayBuffer()
  return { ms: Math.round(performance.now() - t0), ok: res.ok }
}

const probe = async (url) => {
  try {
    await timed(url) // discarded: the first hit may pay a cold start
    const runs = []
    for (let i = 0; i < SAMPLES; i++) runs.push(await timed(url))
    const ok = runs.every((r) => r.ok)
    return ok ? median(runs.map((r) => r.ms)) : null
  } catch {
    return null
  }
}

const history = (() => {
  try {
    const parsed = JSON.parse(readFileSync(join(OUT, 'history.json'), 'utf8'))
    return Array.isArray(parsed) ? parsed : []
  } catch {
    return []
  }
})()

const entry = { t: new Date().toISOString(), ms: {} }
for (const { key, url } of TARGETS) entry.ms[key] = await probe(url)
history.push(entry)
const kept = history.slice(-KEEP)
writeFileSync(join(OUT, 'history.json'), JSON.stringify(kept, null, 0) + '\n')

// ---- drawing ---------------------------------------------------------------

const W = 1060, H = 118
const ROW = 46, PAD = 22
const SPARK_X = 300, SPARK_W = 420, SPARK_H = 26

const sparkline = (series, x0, yMid, color) => {
  const values = series.filter((v) => v != null)
  if (values.length < 2) return ''
  const lo = Math.min(...values), hi = Math.max(...values)
  const span = hi - lo || 1
  const step = SPARK_W / (series.length - 1)

  // A failed probe breaks the line rather than being interpolated over, so an
  // outage reads as an outage and not as a fast response.
  const runs = []
  let run = []
  series.forEach((v, i) => {
    if (v == null) {
      if (run.length > 1) runs.push(run)
      run = []
      return
    }
    run.push(`${(x0 + i * step).toFixed(1)},${(yMid + SPARK_H / 2 - ((v - lo) / span) * SPARK_H).toFixed(1)}`)
  })
  if (run.length > 1) runs.push(run)

  return runs
    .map((r) => `<polyline points="${r.join(' ')}" fill="none" stroke="${color}" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" opacity="0.85"/>`)
    .join('')
}

const build = ({ bg, text, muted, cold, warm, edge, grid }) => {
  const stamp = kept.at(-1).t.replace('T', ' ').slice(0, 16) + ' UTC'
  const rows = TARGETS.map(({ key }, i) => {
    const y = PAD + 20 + i * ROW
    const series = kept.map((e) => e.ms?.[key] ?? null)
    const latest = series.at(-1)
    const value = latest == null ? 'unreachable' : `${latest} ms`
    return `
    <text x="${PAD + 14}" y="${y + 5}" font-size="13.5" fill="${text}" font-family="ui-monospace, monospace">${key}</text>
    <line x1="${PAD + 14}" y1="${y + 18}" x2="${W - PAD - 14}" y2="${y + 18}" stroke="${grid}" stroke-width="1"/>
    ${sparkline(series, SPARK_X, y - 5, cold)}
    <text x="${W - PAD - 14}" y="${y + 5}" text-anchor="end" font-size="15" font-weight="600" font-family="ui-monospace, monospace" fill="${latest == null ? muted : warm}">${value}</text>`
  })

  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${H}" width="${W}" height="${H}" role="img" aria-label="Median response time of the two live demos, measured from GitHub's runners: ${TARGETS.map(({ key }) => `${key} ${kept.at(-1).ms?.[key] ?? 'unreachable'}`).join(', ')} milliseconds.">
  <!-- Generated by scripts/measure.mjs. Do not edit: the next run overwrites it. -->
  <rect x="0" y="0" width="${W}" height="${H}" rx="18" fill="${bg}"/>
  <text x="${PAD + 14}" y="${PAD + 2}" font-size="11" letter-spacing="2.2" fill="${cold}" font-family="ui-monospace, monospace">MEASURED, NOT CLAIMED</text>
  <text x="${W - PAD - 14}" y="${PAD + 2}" text-anchor="end" font-size="11" fill="${muted}" font-family="ui-monospace, monospace">median of ${SAMPLES} · ${stamp}</text>
  ${rows.join('')}
  <rect x="0.75" y="0.75" width="${W - 1.5}" height="${H - 1.5}" rx="18" fill="none" stroke="${edge}" stroke-width="1.5"/>
</svg>
`
}

writeFileSync(join(OUT, 'latency.svg'), build({
  bg: '#0D1117', text: '#E8EDF2', muted: '#97A3B4', cold: '#38BDF8', warm: '#FBBF24', edge: '#2A313C', grid: '#1D2530'
}))
writeFileSync(join(OUT, 'latency-light.svg'), build({
  bg: '#FFFFFF', text: '#12171D', muted: '#57646F', cold: '#0284C7', warm: '#B45309', edge: '#D8DEE6', grid: '#EAEEF2'
}))

console.log(TARGETS.map(({ key }) => `${key}: ${entry.ms[key] ?? 'unreachable'}`).join('  ·  '))
